# Generated by Django 2.0 on 2019-11-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRDType',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('prdtypename', models.CharField(db_column='PRDTypeName', max_length=50)),
            ],
            options={
                'db_table': 'prd_type',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='rwcalevel1',
            table='ca_level1',
        ),
        migrations.AlterModelTable(
            name='verification',
            table='verification',
        ),
    ]
